ALTER TABLE public.public_leads 
  ADD COLUMN IF NOT EXISTS utm_term text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS utm_content text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS referrer text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS landing_page text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS origem_canal text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS device text DEFAULT NULL;